server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service # The name of the application, used by the config server to filter the configuration
  config:
    import: "optional:configserver:" # Imports configuration data from a config server when available
  cloud:
    config:
      uri: http://localhost:8888 # URL of the config server

polar:
  greeting: Welcome to the local book catalog!
